/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EnderecoRouteImport } from './routes/endereco'
import { Route as VentiladorRouteImport } from './routes/ventilador'
import { Route as VentiladorIndexRouteImport } from './routes/ventilador.index'
import { Route as VentiladorCheckoutRouteImport } from './routes/ventilador.checkout'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EnderecoRoute = EnderecoRouteImport.update({
  id: '/endereco',
  path: '/endereco',
  getParentRoute: () => rootRouteImport,
} as any)
const VentiladorRoute = VentiladorRouteImport.update({
  id: '/ventilador',
  path: '/ventilador',
  getParentRoute: () => rootRouteImport,
} as any)
const VentiladorIndexRoute = VentiladorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => VentiladorRoute,
} as any)
const VentiladorCheckoutRoute = VentiladorCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => VentiladorRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/endereco': typeof EnderecoRoute
  '/ventilador': typeof VentiladorRouteWithChildren
  '/ventilador/checkout': typeof VentiladorCheckoutRoute
  '/ventilador/': typeof VentiladorIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/endereco': typeof EnderecoRoute
  '/ventilador/checkout': typeof VentiladorCheckoutRoute
  '/ventilador': typeof VentiladorIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/endereco': typeof EnderecoRoute
  '/ventilador': typeof VentiladorRouteWithChildren
  '/ventilador/checkout': typeof VentiladorCheckoutRoute
  '/ventilador/': typeof VentiladorIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/endereco' | '/ventilador' | '/ventilador/checkout' | '/ventilador/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/endereco' | '/ventilador/checkout' | '/ventilador'
  id:
    | '__root__'
    | '/'
    | '/endereco'
    | '/ventilador'
    | '/ventilador/checkout'
    | '/ventilador/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EnderecoRoute: typeof EnderecoRoute
  VentiladorRoute: typeof VentiladorRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/endereco': {
      id: '/endereco'
      path: '/endereco'
      fullPath: '/endereco'
      preLoaderRoute: typeof EnderecoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ventilador': {
      id: '/ventilador'
      path: '/ventilador'
      fullPath: '/ventilador'
      preLoaderRoute: typeof VentiladorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ventilador/': {
      id: '/ventilador/'
      path: '/'
      fullPath: '/ventilador/'
      preLoaderRoute: typeof VentiladorIndexRouteImport
      parentRoute: typeof VentiladorRoute
    }
    '/ventilador/checkout': {
      id: '/ventilador/checkout'
      path: '/checkout'
      fullPath: '/ventilador/checkout'
      preLoaderRoute: typeof VentiladorCheckoutRouteImport
      parentRoute: typeof VentiladorRoute
    }
  }
}

interface VentiladorRouteChildren {
  VentiladorCheckoutRoute: typeof VentiladorCheckoutRoute
  VentiladorIndexRoute: typeof VentiladorIndexRoute
}

const VentiladorRouteChildren: VentiladorRouteChildren = {
  VentiladorCheckoutRoute: VentiladorCheckoutRoute,
  VentiladorIndexRoute: VentiladorIndexRoute,
}

const VentiladorRouteWithChildren = VentiladorRoute._addFileChildren(
  VentiladorRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EnderecoRoute: EnderecoRoute,
  VentiladorRoute: VentiladorRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
